name: Build, Push, and Update Deployment

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-push-update:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the Service Repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub (or another container registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Step 3: Build and push the Docker image
      - name: Build and push Docker image
        run: |
          docker build -t dedinededin/flask-app:$GITHUB_SHA .
          docker push dedinededin/flask-app:$GITHUB_SHA

      # Step 4: Checkout the Deployment Repository
      - name: Checkout Deployment Repository
        uses: actions/checkout@v3
        with:
          repository: ibrahim-dogan/argo-cd-poc  # Replace with your Deployment Repository
          token: ${{ secrets.GITHUB_TOKEN }}
          path: deployment-repo

      # Step 5: Update the Kubernetes manifest with the new image tag
      - name: Update Kubernetes Manifest
        run: |
          cd deployment-repo
          sed -i "s|dedinededin/flask-app:.*|dedinededin/flask-app:$GITHUB_SHA|g" manifests/deployment.yaml
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add manifests/deployment.yaml
          git commit -m "Update image to $GITHUB_SHA"
          git push