name: Build, Push, and Update Deployment

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  workflow_dispatch:  # Allow manual triggering for prod deployment

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the Service Repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub (or another container registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Step 3: Build and push the Docker image
      - name: Build and push Docker image
        run: |
          docker build -t dedinededin/flask-app:$GITHUB_SHA .
          docker push dedinededin/flask-app:$GITHUB_SHA

  update-dev-deployment:
    runs-on: ubuntu-latest
    needs: build-and-push  # Run this job after the build-and-push job
    steps:
      # Step 1: Checkout the Deployment Repository
      - name: Checkout Deployment Repository
        uses: actions/checkout@v3
        with:
          repository: ibrahim-dogan/argo-cd-poc  # Replace with your Deployment Repository
          token: ${{ secrets.DEPLOYMENT_REPO_TOKEN }}
          path: argo-cd-poc

      # Step 2: Update the dev Kubernetes manifests with the new image tag
      - name: Update Dev Kubernetes Manifests
        run: |
          cd argo-cd-poc
          sed -i "s|dedinededin/flask-app:.*|dedinededin/flask-app:$GITHUB_SHA|g" manifests/overlays/dev/flask-patch.yaml
          
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add manifests/overlays/dev/flask-patch.yaml
          git commit -m "Update flask-app image to $GITHUB_SHA in dev environment"
          git push

  update-prod-deployment:
    runs-on: ubuntu-latest
    needs: update-dev-deployment  # Run this job after the dev deployment
    if: github.event_name == 'workflow_dispatch'  # Trigger only on manual dispatch
    steps:
      # Step 1: Checkout the Deployment Repository
      - name: Checkout Deployment Repository
        uses: actions/checkout@v3
        with:
          repository: ibrahim-dogan/argo-cd-poc  # Replace with your Deployment Repository
          token: ${{ secrets.DEPLOYMENT_REPO_TOKEN }}
          path: argo-cd-poc

      # Step 2: Update the prod Kubernetes manifests with the new image tag
      - name: Update Prod Kubernetes Manifests
        run: |
          cd argo-cd-poc
          sed -i "s|dedinededin/flask-app:.*|dedinededin/flask-app:$GITHUB_SHA|g" manifests/overlays/prod/flask-patch.yaml
          
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add manifests/overlays/prod/flask-patch.yaml
          git commit -m "Update flask-app image to $GITHUB_SHA in prod environment"
          git push
